from Schedule import Schedule
from Person import Person

if __name__ == "__main__":
    # Create test employees
    employees = [
    Person(
        name="Andrea",
        availability={
            "Monday": [False, True],
            "Tuesday": [False, False],
            "Wednesday": [False, True],
            "Thursday": [False, False],
            "Friday": [False, True],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=True,
        maxShift=3,
        minShift=0,
    ),
    Person(
        name="Andrew Chao",
        availability={
            "Monday": [False, False],
            "Tuesday": [False, True],
            "Wednesday": [False, False],
            "Thursday": [False, True],
            "Friday": [True, True],
            "Saturday": [True, True],
            "Sunday": [True, True],
        },
        isSoup=True,
        maxShift=4,
        minShift=3,
    ),
    Person(
        name="Athena Chen",
        availability={
            "Monday": [False, False],
            "Tuesday": [True, False],
            "Wednesday": [False, False],
            "Thursday": [False, True],
            "Friday": [True, True],
            "Saturday": [True, True],
            "Sunday": [True, True],
        },
        isSoup=True,
        maxShift=3,
        minShift=2,
    ),
    Person(
        name="Chester Ho",
        availability={
            "Monday": [True, False],
            "Tuesday": [True, False],
            "Wednesday": [True, False],
            "Thursday": [True, False],
            "Friday": [True, False],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=True,
        maxShift=3,
        minShift=3,
    ),
    Person(
        name="Dan",
        availability={
            "Monday": [True, True],
            "Tuesday": [False, True],
            "Wednesday": [False, True],
            "Thursday": [False, True],
            "Friday": [True, True],
            "Saturday": [True, True],
            "Sunday": [False, False],
        },
        isSoup=True,
        maxShift=3,
        minShift=2,
    ),
    Person(
        name="Destiny",
        availability={
            "Monday": [False, False],
            "Tuesday": [True, True],
            "Wednesday": [False, False],
            "Thursday": [True, True],
            "Friday": [True, True],
            "Saturday": [True, True],
            "Sunday": [True, True],
        },
        isSoup=False,
        maxShift=4,
        minShift=3,
    ),
    Person(
        name="Donny Chen",
        availability={
            "Monday": [False, True],
            "Tuesday": [False, True],
            "Wednesday": [False, True],
            "Thursday": [False, False],
            "Friday": [False, False],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=False,
        maxShift=2,
        minShift=0,
    ),
    Person(
        name="Elissa Early",
        availability={
            "Monday": [True, False],
            "Tuesday": [True, False],
            "Wednesday": [True, False],
            "Thursday": [True, False],
            "Friday": [True, False],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=True,
        maxShift=4,
        minShift=1,
    ),
    Person(
        name="Ian Jo",
        availability={
            "Monday": [False, False],
            "Tuesday": [False, False],
            "Wednesday": [True, True],
            "Thursday": [False, False],
            "Friday": [True, True],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=False,
        maxShift=2,
        minShift=1,
    ),
    Person(
        name="Imogene",
        availability={
            "Monday": [False, True],
            "Tuesday": [True, True],
            "Wednesday": [False, True],
            "Thursday": [True, True],
            "Friday": [False, True],
            "Saturday": [True, False],
            "Sunday": [True, True],
        },
        isSoup=False,
        maxShift=4,
        minShift=3,
    ),
    Person(
        name="Jacob Sinn",
        availability={
            "Monday": [True, False],
            "Tuesday": [False, True],
            "Wednesday": [False, False],
            "Thursday": [False, False],
            "Friday": [True, True],
            "Saturday": [True, True],
            "Sunday": [True, True],
        },
        isSoup=True,
        maxShift=2,
        minShift=1,
    ),
    Person(
        name="Josh Rodriguez",
        availability={
            "Monday": [True, True],
            "Tuesday": [False, True],
            "Wednesday": [False, True],
            "Thursday": [False, False],
            "Friday": [True, True],
            "Saturday": [False, False],
            "Sunday": [False, False],
        },
        isSoup=False,
        maxShift=4,
        minShift=3,
    ),
    Person(
        name="Karen Resendiz",
        availability={
            "Monday": [False, False],
            "Tuesday": [False, True],
            "Wednesday": [False, True],
            "Thursday": [False, True],
            "Friday": [True, True],
            "Saturday": [False, True],
            "Sunday": [True, True],
        },
        isSoup=True,
        maxShift=3,
        minShift=3,
    ),
    Person(
        name="Kayla Vu",
        availability={
            "Monday": [False, False],
            "Tuesday": [True, False],
            "Wednesday": [False, True],
            "Thursday": [True, True],
            "Friday": [True, True],
            "Saturday": [False, False],
            "Sunday": [True, False],
        },
        isSoup=True,
        maxShift=2,
        minShift=1,
    ),
    Person(
        name="Lester San Juan",
        availability={
            "Monday": [False, False],
            "Tuesday": [False, True],
            "Wednesday": [True, True],
            "Thursday": [False, False],
            "Friday": [True, True],
            "Saturday": [False, True],
            "Sunday": [True, True],
        },
        isSoup=False,
        maxShift=2,
        minShift=2,
    ),
    Person(
        name="Vaughn Payumo",
        availability={
            "Monday": [False, False],
            "Tuesday": [True, True],
            "Wednesday": [True, True],
            "Thursday": [False, False],
            "Friday": [False, True],
            "Saturday": [True, True],
            "Sunday": [False, True],
        },
        isSoup=False,
        maxShift=2,
        minShift=1,
    ),
]

    # Create a schedule and populate it
    schedule = Schedule()
    schedule.fillShiftsGreedy(employees)

    # Print the filled schedule
    print(schedule)